name: Keepalive Workflow

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    permissions:
      actions: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Keep scheduled workflows active
        uses: gautamkrishnar/keepalive-workflow@v2
        with:
          workflow_files: 'update-gateway.yml'
